global_costmap:

    global_frame: map # map
    robot_base_frame: base_footprint # base_link

    update_frequency: 10.0
    publish_frequency: 10.0
    transform_tolerance: 0.5

    static_map: true
    rolling_window: true

    width: 30.0
    height: 30.0
    resolution: 0.05
