map_type: costmap
transform_tolerance: 0.2
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.38
# robot_radius: 0.3

footprint:
  [ [ 0.27,  0.26],
    [ 0.27, -0.26],
    [-0.27, -0.26],
    [-0.27,  0.26] ]

observation_sources: laser_scan_front_observation
# laser_scan_back_observation
# point_cloud_front_observation

laser_scan_front_observation: {
    sensor_frame: base_scan_front,
    data_type: LaserScan,
    topic: base_scan_front,
    expected_update_rate: 0.2,
    marking: true,
    clearing: true,
}

laser_scan_back_observation: {
    sensor_frame: base_scan_back,
    data_type: LaserScan,
    topic: base_scan_back,
    expected_update_rate: 0.2,
    marking: true,
    clearing: true,
}

point_cloud_front_observation: {
    sensor_frame: xtion_depth_optical,
    data_type: PointCloud2,
    topic: xtion/depth/points,
    expected_update_rate: 0.2,
    marking: true,
    clearing: true,
    max_obstacle_height: 2.5,
    min_obstacle_height: 0.035,
  }
